<?php

return [
    'STRUCTURED_DATA_TESTING_TOOL_SUBJECT_SUCCESS' => 'required',
    'STRUCTURED_DATA_TESTING_TOOL_SUBJECT_ALARM' => 'required',
    'STRUCTURED_DATA_TESTING_TOOL_MESSAGE_FROM' => 'required|email',
    'STRUCTURED_DATA_TESTING_TOOL_MESSAGE_FROM_NAME' => 'required',
    'STRUCTURED_DATA_TESTING_TOOL_MAIL_VIEW_NAME' => 'required',
    'STRUCTURED_DATA_TESTING_TOOL_LOG_FILE_PATH' => 'required',
];
